version: '3.8'

services:
  backend:
    container_name: insta_business_media_management_api
    image: azizisgandarzada20/insta-business-media-management-api:1.0.0
    environment:
      DB_USERNAME: <DB_USERNAME>
      DB_PASSWORD: <DB_PASSWORD>
      DB_HOST: <DB_HOST>
      DB_PORT: <DB_PORT>
      DB_NAME: <DB_NAME>
      INSTAGRAM_GRAPH_URL: <INSTAGRAM_GRAPH_URL>
      INSTAGRAM_ACCESS_TOKEN: <INSTAGRAM_ACCESS_TOKEN>
      INSTAGRAM_BUSINESS_ID: <INSTAGRAM_BUSINESS_ID>
      INSTAGRAM_CHECK_STATUS_ATTEMPTS: <INSTAGRAM_CHECK_STATUS_ATTEMPTS>
      INSTAGRAM_CHECK_STATUS_INTERVAL: <INSTAGRAM_CHECK_STATUS_INTERVAL>
      TELEGRAM_BOT_TOKEN: <TELEGRAM_BOT_TOKEN>
      TELEGRAM_ALLOWED_CHAT_ID: <TELEGRAM_ALLOWED_CHAT_ID>
    networks:
      - postgres_db
  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: <POSTGRES_USER>
      POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
      POSTGRES_DB: <POSTGRES_DB>
      PGDATA: /var/lib/postgres_db/data
    volumes:
      - postgres_db:/var/lib/postgres_db/data
    ports:
      - "5432:5432"
    networks:
      - postgres_db
