client:
  instagram-graph:
    url: ${INSTAGRAM_GRAPH_URL}
    credentials:
      access-token: ${INSTAGRAM_ACESS_TOKEN}
  telegram-tk-bot:
    credentials:
      token: ${TELEGRAM_BOT_TOKEN}
      allowed-chat-id: ${TELEGRAM_ALLOWED_CHAT_ID}